name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    steps:
      - uses: ./.github/workflows/reusable-workflow.yml
      - with:
          node: ${{ matrix.nodeversion }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
